version: '3.9'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress   
    command: 
      - /bin/sh
      - -c
      - |
        a2enmod rewrite && a2enmod ssl && a2enmod socache_shmcb
        sed -i 's/ssl-cert-snakeoil.pem/${SSL_CERT}/g' /etc/apache2/sites-available/default-ssl.conf
        sed -i 's/ssl-cert-snakeoil.key/${SSL_KEY}/g' /etc/apache2/sites-available/default-ssl.conf
        a2ensite default-ssl
        apache2-foreground
    volumes:
      - ./wordpress:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/ssl/${SSL_KEY}:/etc/ssl/private/${SSL_KEY}
      - ./config/ssl/${SSL_CERT}:/etc/ssl/certs/${SSL_CERT}
  
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db/data:/var/lib/mysql
