version: '3.9'

services:

  db:
    env_file: .env
    image: mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db/data:/var/lib/mysql

  wordpress:
    env_file: .env
    image: wordpress:fpm
    restart: unless-stopped
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    env_file: .env
    image: nginx
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_SSL_CERT=${SSL_CERT}
      - NGINX_SSL_CERT_KEY=${SSL_CERT_KEY}
    volumes:
      - ./config/ssl/${SSL_CERT_KEY}:/etc/ssl/${SSL_CERT_KEY}
      - ./config/ssl/${SSL_CERT}:/etc/ssl/${SSL_CERT}
      - ./config/nginx/templates:/etc/nginx/templates
      - ./wordpress:/var/www/html
